name: Maven Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Setup Java environment
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adoptopenjdk'

    # List the files in the repository to debug path issues
    - name: List directory contents
      run: ls -R

    # Run Maven build and tests
    - name: Build with Maven
      run: mvn clean install

    - name: Run tests with Maven
      run: mvn test
