name: Maven Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for this job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout your repository

      - name: Set up Java JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Specify the Java version to use
          distribution: 'temurin'  # Correct JDK distribution

      - name: Set up Chrome Driver
        uses: actions/checkout@v2  # Checkout your repository
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget -N https://chromedriver.storage.googleapis.com/116.0.5845.96/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          
      - name: Install dependencies and run Selenium tests
        run: |
          cd SeleniumFramework  # Navigate to the directory containing the `pom.xml` file
          mvn test  # Run Selenium test cases as specified in your test files
