name: Print Working Directory

on: [push]

jobs:
  print-directory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Print working directory
        run: echo "Current Working Directory:$(pwd)"
