name: Maven Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  maven-build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for this job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout your repository

      - name: Set up Java JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Specify the Java version to use
          distribution: 'temurin'  # Correct distribution for JDK 11 from Adoptium

      - name: Navigate to the correct directory
        run: cd SeleniumFramework  # Change directory to the folder containing your pom.xml

      - name: Install dependencies and run tests
        run: mvn clean install  # Run Maven to clean, install dependencies, and run tests

      - name: Print working directory (optional)
        run: echo "Current Working Directory:$(ls -R)"  # List directory structure (optional)
