name: Run Selenium Test with Results in Console

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout your repository

      - name: Set up Java JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Specify the Java version to use
          distribution: 'temurin'  # Correct JDK distribution

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable  # Install Google Chrome
          sudo apt-get install -y chromium-chromedriver  # Install ChromeDriver
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

      - name: Run specific Selenium test
        run: |
          cd SeleniumFramework  # Navigate to the directory containing the `pom.xml` file
          mvn clean test -B -Dtest=Complete_Registartion_login_Form  # Run only the specific test file in batch mode
          cat target/surefire-reports/result123.txt  # Output test results to the console
