name: Run All Selenium Tests with Cron Job

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch
  schedule:
- cron: '15 13 * * *'  # Run daily at 1:15 PM UTC (6:15 PM PKT)
- cron: '15 14 * * *'  # Run daily at 2:15 PM UTC (7:15 PM PKT)

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -y chromium-chromedriver
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

      - name: Run specific Selenium tests
        run: |
          cd SeleniumFramework
          mvn clean test -B -Dtest=Complete_Registartion_login_Form,Complete_Registration_Login_Seller,Complete_Registration_login_Both
          echo "Test results:"
          cat target/surefire-reports/*.txt
