name: Maven Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Set up Java JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Cache Maven dependencies to speed up the build process
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: C:\Users\RunnerAdmin\.m2\repository
          key: ${{ runner.os }}-maven-${{ hashFiles('/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Install dependencies and run tests using Maven
      - name: Build and Test with Maven
        run: mvn clean install
        working-directory: ./SeleniumFramework


      # Run TestNG tests
      - name: Run TestNG Tests
        run: mvn test
