name: Run Selenium Test

on:
  push:
    branches:
      - main

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
            - name: SeleniumCICD
  # You may pin to the exact commit or the version.
  # uses: nakajiss/DockerSeleniumAction@e6ea7ae921226473af620875a8853bad0750a033
  uses: nakajiss/DockerSeleniumAction@v1.3.7
  with:
    # python test plan to execute
    test-plan-path: 
    # Optional arguments.
    args: # optional
          
      - name: Install Maven dependencies
        run: mvn install

      - name: Run Selenium Test
        run: mvn test -Dtest=Complete_Registartion_login_Form
